name: Backend CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  npm-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "install deps and run checks"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt && pip install -r requirements.dev.txt
          black --check .
          flake8
          mypy app/
