name: Frontend CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies and run checks
        run: |
          npm i --legacy-peer-deps
          npm run check
