name: Frontend CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  npm-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "npm"
          working-directory: frontend/

      - name: Install dependencies and run checks
        working-directory: frontend/
        run: |
          npm ci
          npm run check
