name: Frontend CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  npm-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "npm"

      - run: cd frontend
      - run: npm ci
      - run: npm run check
